site_name: Demo IS1 - Ingeniería de Software I
site_url: https://262is1.github.io/demo-is1/
docs_dir: docs

nav:
  - Inicio: index.md
  - Sílabos:
      - Sílabo IS1 2026-1: silabo_is1_2026_1.md
      - Sílabo IS1 2026-2: silabo_is1_2026_2.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

plugins:
  - search
